{% set name = "glmnet_py" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/johnlees/glmnet_python/archive/v{{ version }}.tar.gz
  sha256: c6bd4f60daa70ad2d2297ae804a2e2e5ab22021af6c14b3a288f94965c613196

build:
  number: 0
  skip: true  # [win or py2k]

requirements:
  build:
    - {{ compiler('fortran') }}

  host:
    - python
    - pip

  run:
    - python
    - joblib >=0.10.3
    - scipy
    - matplotlib

test:
  imports:
    - glmnet_python
    - glmnet_python.glmnet
    - glmnet_python.glmnetPlot
    - glmnet_python.glmnetPrint
    - glmnet_python.glmnetCoef
    - glmnet_python.glmnetPredict
    - glmnet_python.cvglmnet
    - glmnet_python.cvglmnetCoef
    - glmnet_python.cvglmnetPlot
    - glmnet_python.cvglmnetPredict

about:
  home: https://github.com/bbalasub1/glmnet_python
  license: GPL-2
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'python version of the popular glmnet library'
  description: |
    This is a python version of the popular glmnet library (beta release).
    Glmnet fits the entire lasso or elastic-net regularization path for
    linear regression, logistic and multinomial regression models, poisson
    regression and the cox model.
  doc_url: http://glmnet-python.readthedocs.io/
  dev_url: https://github.com/bbalasub1/glmnet_python

extra:
  recipe-maintainers:
    - johnlees
