{% set name = "glmnet_py" %}
{% set version = "1.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/johnlees/glmnet_python/archive/v{{ version }}.tar.gz
  sha256: 50a43a91ff10def588ad619d652fa8763f31c5656dd6079c2409809bf4f2058f
  patches:
    - 0001-setup.py-for-conda-gfortran.patch

build:
  number: 1
  skip: true  # [win or py2k]
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  build:
    - {{ compiler('fortran') }}

  host:
    - python
    - pip

  run:
    - python
    - joblib >=0.10.3
    - numpy
    - scipy
    - matplotlib-base

test:
  imports:
    - glmnet_python
    - glmnet_python.glmnet
    - glmnet_python.glmnetPlot
    - glmnet_python.glmnetPrint
    - glmnet_python.glmnetCoef
    - glmnet_python.glmnetPredict
    - glmnet_python.cvglmnet
    - glmnet_python.cvglmnetCoef
    - glmnet_python.cvglmnetPlot
    - glmnet_python.cvglmnetPredict

about:
  home: https://github.com/bbalasub1/glmnet_python
  license: GPL-2
  license_family: GPL
  license_file: LICENSE.txt
  summary: 'python version of the popular glmnet library'
  description: |
    This is a python version of the popular glmnet library (beta release).
    Glmnet fits the entire lasso or elastic-net regularization path for
    linear regression, logistic and multinomial regression models, poisson
    regression and the cox model.
  doc_url: http://glmnet-python.readthedocs.io/
  dev_url: https://github.com/bbalasub1/glmnet_python

extra:
  recipe-maintainers:
    - johnlees
